# Generated by Django 6.0.6 on 2026-09-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_requestlog_cached_tokens_requestlog_first_token_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='allowed_models',
            field=models.JSONField(blank=True, default=list, help_text='model names this key may call; empty list = all enabled models'),
        ),
    ]
