# Generated by Django 6.0.6 on 2026-09-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userapikey_allowed_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='group',
        ),
        migrations.DeleteModel(
            name='ProxyGroup',
        ),
    ]
